lena:
	@python ./main.py ./pictures/Lena512.bmp
boat:
	@python ./main.py ./pictures/Boat512.bmp
tank:
	@python ./main.py ./pictures/Tank256.bmp
cameraman:
	@python ./main.py ./pictures/Cameraman1024.bmp
ctscan:
	@python ./main.py ./pictures/CT1024.bmp
